backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "stage"
    label: "Stage"
    folder: "content/stage"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "background", widget: "image", choose_url: true, default: "../../images/uploads/lion-lrw.png" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "textmedia"
    label: "Text-Media"
    folder: "content/text-media"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Select", name: "select", widget: "select", options: ["Design", "UX", "Dev"] }

